name: 🚀 Deploy vía FTP desde rama deploy

on:
  push:
    branches:
      - deploy

jobs:
  ftp-deploy:
    name: 📤 Subida por FTP
    runs-on: ubuntu-latest
    environment: FTP

    steps:
    - name: 🔍 Checkout del código
      uses: actions/checkout@v3
      

    - name: 📤 Subir por FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: ${{ secrets.FTP_TARGET }}/
        dangerous-clean-slate: false

        # 🔐 Plesk trabaja mejor con FTPS 
        protocol: ftps 
        port: 21 
        passive: true 
        # ⏱️ Evitar cortes (muy común en Plesk) 
        timeout: 600000 
        # 🧪 Logs para depuración 
        log-level: verbose   

        # 🚫 EXCLUIR ARCHIVOS INNECESARIOS 
        exclude: |
          **/.git*
          **/.git*/**
          **/.vscode/**
          **/node_modules/**
